name: GitHubCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: docker://multiarch/ubuntu-core:arm64-bionic
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libncursesw5-dev libreadline-dev qemu-user-static
      - name: Build with make
        run: |
          sudo make strip install
      - name: Upload built executable
        uses: actions/upload-artifact@v3
        with:
          name: nnn-executable
          path: /usr/local/bin/nnn
