name: GitHubCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libncursesw5-dev libreadline-dev
      - name: Build with make
        run: |
          sudo make strip install
